# Generated by Django 5.0.4 on 2024-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Administrator')], default='CUSTOMER', max_length=15),
        ),
    ]
