# Generated by Django 5.0.4 on 2024-05-09 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_user_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures')),
                ('state', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('phone_number', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.RemoveField(
            model_name='targetsaving',
            name='user',
        ),
        migrations.RemoveField(
            model_name='targetsaving',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='PersonalLoan',
        ),
        migrations.DeleteModel(
            name='TargetSaving',
        ),
    ]
