# Generated by Django 5.0.4 on 2024-05-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_personalloan_targetsaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalloan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], default='Pending', max_length=100),
        ),
        migrations.DeleteModel(
            name='TargetSaving',
        ),
    ]
