# Generated by Django 5.0.4 on 2024-05-28 08:30

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_personalloan_status_delete_targetsaving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_age', models.PositiveIntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('loan_purpose', models.TextField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_documents', models.BooleanField()),
                ('repayment_duration', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseFinancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=255)),
                ('equipment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_funding', models.BooleanField()),
                ('acquisition_timeline', models.CharField(max_length=100)),
                ('has_documents', models.BooleanField()),
                ('repayment_duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+!#,~-%&*£', length=12, max_length=40, prefix='NBL_')),
                ('amount', models.CharField(max_length=10)),
                ('start_save', models.DateField()),
                ('save_by', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
