# Generated by Django 5.0.4 on 2024-05-28 09:02

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_corporateloan_leasefinancing_targetsaving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporateloan',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='leasefinancing',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='corporateloan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='corporateloan',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+!#,~-%&*£', length=12, max_length=40, prefix='NBL_'),
        ),
        migrations.AddField(
            model_name='leasefinancing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='leasefinancing',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+!#,~-%&*£', length=12, max_length=40, prefix='NBL_'),
        ),
        migrations.AlterField(
            model_name='targetsaving',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], default='Pending', max_length=100),
        ),
    ]
