# Generated by Django 5.0.4 on 2024-05-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_user_corporateloan_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateloan',
            name='has_documents',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='leasefinancing',
            name='has_documents',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='leasefinancing',
            name='has_funding',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
