# Generated by Django 5.0.4 on 2024-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_corporateloan_has_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateloan',
            name='has_documents',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='leasefinancing',
            name='has_documents',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='leasefinancing',
            name='has_funding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
