# Generated by Django 5.0.4 on 2024-05-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_corporateloan_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateloan',
            name='document_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leasefinancing',
            name='document_link',
            field=models.URLField(blank=True),
        ),
    ]
